# SPDX-FileCopyrightText: LoopBack Contributors
# SPDX-License-Identifier: MIT

bracketSpacing: false
singleQuote: true
printWidth: 80
trailingComma: all
arrowParens: avoid
overrides:
  - files: '**/*.md'
    options:
      parser: markdown
      proseWrap: always
