#!/bin/sh
# SPDX-FileCopyrightText: LoopBack Contributors
# SPDX-License-Identifier: MIT

. "$(dirname "$0")/_/husky.sh"

npm run-script prettier:check
npm run-script validate-csaf20
npm run-script validate-osv
