# SPDX-FileCopyrightText: LoopBack Contributors
# SPDX-License-Identifier: MIT

name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
          npm run-script --ignore-scripts install
      - name: Build project
        run: npm run --ignore-scripts build
      - name: Code lint check
        run: |
          npm run-script --ignore-scripts prettier:check
          npm run-script --ignore-scripts validate
      - name: REUSE compliance check
        uses: fsfe/reuse-action@43bd643263f2a557a37e023e538ab9f83dce92a6 #v1.1.1
  commit-lint:
    name: Commit Lint
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Commit lint check
        run: npx --no-install commitlint --from=origin/main --to=HEAD --verbose
