name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: |
          npm run-script --ignore-scripts prettier:check
          npm run-script --ignore-scripts validate-csaf20
  commit-lint:
    name: Commit Lint
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Tools
        run: npm ci --ignore-scripts
      - run: npx commitlint --from=origin/master --to=HEAD --verbose
